const client = require('./db/database');
const studentstable = 'CREATE TABLE student(ID INT PRIMARY KEY NOT NULL,FNAME TEXT,LNAME TEXT,EMAIL CHAR(100),PASSWORD REAL,BYEAR INT,DOB CHAR(10),LOCATION INT,PAREA INT,HOUSE CHAR(50),LANDMARK CHAR(100),ADDRESS TEXT,EIRCODE CHAR(100),LICENSE CHAR(100),GENDER INT,TRANSMISSTION INT,POINTS INT,PHOTO CHAR(1000),DOCUMENT CHAR(1000),STATUS INT);';
const teacherstable = 'CREATE TABLE teacher(ID INT PRIMARY KEY NOT NULL,FNAME TEXT,LNAME TEXT,EMAIL CHAR(100),PASSWORD REAL,BYEAR INT,DOB CHAR(10),LOCATION INT,AREAS INT,HOUSE CHAR(50),LANDMARK CHAR(100),ADDRESS TEXT,EIRCODE CHAR(100),LICENSE CHAR(100),GENDER INT,TRANSMISSTION INT,POINTS INT,PHOTO CHAR(1000),DOCUMENT CHAR(1000),STATUS INT);';
const bookings = 'CREATE TABLE bookings(ID INT PRIMARY KEY,TID INT,SID INT,TNAME TEXT,SNAME TEXT,PRICE INT,DATE CHAR(10),LOCATION INT,STATUS INT)';
const ratings = 'CREATE TABLE ratings(ID INT PRIMARY KEY,TID INT,SID INT,TNAME TEXT,SNAME TEXT,DATE CHAR(10),STARS INT,REVIEW CHAR(500))';
const purchases = 'CREATE TABLE purchases(ID INT PRIMARY KEY,UID INT, NAME TEXT,POINTS INT,PRICE INT,UTYPE INT,DATE CHAR(10))';
const plans = 'CREATE TABLE plans(ID INT PRIMARY KEY,NAME TEXT,POINTS INT,PRICE INT,UTYPE INT)';
const areas = 'CREATE TABLE areas(ID INT PRIMARY KEY,TOWN TEXT,COUNTRY TEXT)';